/*----------------------------------------------------------------------------+
Copyright (c) 1999-2006: Cortex Software GmbH, Kantstrasse 57, Berlin
+-----------------------------------------------------------------------------+
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
+----------------------------------------------------------------------------*/
/* ------------------------------------------------------------------
Predicates
    general classes for Predicates
--------------------------------------------------------------------*/
#ifndef __itl_PRED_H_JOFA_990224__
#define __itl_PRED_H_JOFA_990224__

namespace itl
{
    
// Unary predicates

template <class ALPHA>
class PropertyT // : public unary_function<ALPHA,bool>
{
public:
    virtual bool operator() (const ALPHA& x)const=0; // { return true; }
} ;

template <class ALPHA>
class PredT : public PropertyT<ALPHA>
{
public:
    PredT( bool(ALPHA::* pred)()const ): PropertyT<ALPHA>(), m_pred(pred){}
    bool operator () (const ALPHA& x)const { return (x.*m_pred)(); }
private:
    bool(ALPHA::* m_pred)()const;
} ;

template <class ALPHA>
class EmptyT: public PropertyT<ALPHA>
{
public:
    bool operator() (const ALPHA& x)const { return x.empty(); }
} ;


// Binary predicates: relations

template <class ALPHA, class BETA>
class RelationT // : public binary_function<ALPHA,bool>
{
public:
    virtual bool operator() (const ALPHA& a, const BETA& b)const { return true; }
} ;

template <class ALPHA>
class SubsetRelationT: public RelationT<ALPHA, ALPHA>
{
public:
    bool operator()(const ALPHA& x1, const ALPHA& x2)const
    { return x1.isSubsetOf(x2); }
} ;

template <class ALPHA>
class IdentityRelationT: public RelationT<ALPHA, ALPHA>
{
public:
    bool operator()(const ALPHA& x1, const ALPHA& x2)const
    { return x1 == x2; }
} ;

template <class ALPHA>
class DisjointRelationT: public RelationT<ALPHA, ALPHA>
{
public:
    bool operator()(const ALPHA& x1, const ALPHA& x2)const
    { return x1.isDisjointTo(x2); }
} ;



template <class DomTV>
class OrderT
{
public:
    virtual bool operator() (const DomTV&, const DomTV&)const=0;
};


} // namespace itl


#endif

