/*----------------------------------------------------------------------------+
Copyright (c) 1999-2006: Cortex Software GmbH, Kantstrasse 57, Berlin
+-----------------------------------------------------------------------------+
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
+----------------------------------------------------------------------------*/

#ifndef __DVarPermutationT_JOFA_040621_H__
#define __DVarPermutationT_JOFA_040621_H__

#include <itl/fixtupelconst.hpp>
#include <vector>
//CL #include <itl/ctxvectort.hpp>

namespace itl
{

    class DVarPermutationT
    {
    private:
        typedef vector<VarEnumTD> PermutationTD;
    public:
        DVarPermutationT(){}
        DVarPermutationT(int capacity);

        int capacity()const { return m_Permutation.capacity(); }
        int size()const { return m_Permutation.size(); }

        DVarPermutationT& add(VarEnumTD var);
        DVarPermutationT& del(int count = 1);

        void setIdentity();
        DVarPermutationT& clear() { m_Permutation.clear(); return *this; }

        /// Liefert zu einem Index der Permutation den urspruenglichen index.
        VarEnumTD operator[] (VarEnumTD permIdx)const { return m_Permutation[permIdx]; }

        DVarPermutationT operator() (VarEnumTD fst, VarEnumTD lst)const;

    private:
        PermutationTD m_Permutation;
    };

}

#endif // __DVarPermutationT_JOFA_040621_H__





