/*----------------------------------------------------------------------------+
Copyright (c) 2007-2008: Joachim Faulhaber
+-----------------------------------------------------------------------------+
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
+----------------------------------------------------------------------------*/
/* ------------------------------------------------------------------
class sets
    a general and generic set interface
--------------------------------------------------------------------*/
#ifndef __sets_H_JOFA_990223__
#define __sets_H_JOFA_990223__

#include <itl/itl_concepts.hpp>

namespace itl
{

/// interface template for sets
/**
    Template interface class <b>sets</b>: Defines a general interface for sets.

    Template parameter <b>DomainT</b>: The set's domain-type. Type of the 
    set's elements.
    
    @author  Joachim Faulhaber
*/
template <class DomainT> class sets
{
public:

    /// virtual destructor
    virtual ~sets(){}

    /// Remove all elements of the set
    virtual void clear()=0;

    /// Is the set empty?
    virtual bool empty()const=0;

    /// Does the set contain the element x?
    virtual bool contains(const DomainT& x)const=0;

    /// Inserts an element x into the set
    virtual void insert(const DomainT& x)=0;

    /// Remove the element x from the set
    virtual void subtract(const DomainT& x)=0;

} ;

} // namespace itl

#endif


