/*----------------------------------------------------------------------------+
Copyright (c) 2007: Joachim Faulhaber
+-----------------------------------------------------------------------------+
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
+----------------------------------------------------------------------------*/
#ifndef __itl_type_traits_h_JOFA_071020__
#define __itl_type_traits_h_JOFA_071020__

namespace itl
{
	/** This file covers type traits that have to be used within law validaton.	*/
	// JODO amalgamate type_traits with AlgBase and ReprBase


	template <typename Type>
	Type abs(Type val) { return val < 0 ? -val : val; }

	template<typename Type>	class value_size
	{
	public:
		//REV static std::size_type get(const Type& val);
		static int get(const Type& val);
	};

	template<> int value_size<int>::get(const int& val) { return abs(val); }
	template<> int value_size<double>::get(const double& val) { return static_cast<int>(abs(val)); }

	template <typename Type> 
	inline int value_size<Type>::get(const Type& val){ return static_cast<int>(val.size()); }

} // namespace itl

#endif //__itl_type_traits_h_JOFA_070411__


