/*----------------------------------------------------------------------------+
Copyright (c) 1999-2006: Cortex Software GmbH, Kantstrasse 57, Berlin
+-----------------------------------------------------------------------------+
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
+----------------------------------------------------------------------------*/
#include <iostream>
#include <string>
#include <itl/ctxreprbase.hpp>
#include <itl/itl_interval.hpp>
#include <math.h>
#include "../toytime.h"

using namespace std;
using namespace itl;

/** Example interval.cpp \file interval.cpp

	Of course much of the library code deals with intervals which are implemented
	as class interval.

	This program gives a very short samlpe of different interval instances.

    \include interval/interval.cpp
*/
int main()
{
	cout << ">> Interval Template Library: Sample interval.cpp <<\n";
	cout << "---------------------------------------------------\n";

	interval<int>    int_Itv  = closed_interval(3,7);
	interval<double> sqrt_Itv = rightopen_interval(1/sqrt(2.0), sqrt(2.0));
	interval<string> city_Itv = leftopen_interval<string>("Barcelona", "Boston");
	interval<Time>   time_Itv = open_interval(Time(monday,8,30), Time(monday,17,20));

	cout << "Interval<int>: " << int_Itv.asString() << endl;
	cout << "Interval<double>: " << sqrt_Itv.asString() << " does " 
		                         << string(sqrt_Itv.contains(sqrt(2.0))?"":"NOT") << " contain sqrt(2)" << endl;
	cout << "Interval<string>: " << city_Itv.asString() << " does "  
	                             << string(city_Itv.contains("Barcelona")?"":"NOT") << " contain 'Barcelona'" << endl;
	cout << "Interval<string>: " << city_Itv.asString() << " does "  
	                             << string(city_Itv.contains("Berlin")?"":"NOT") << " contain 'Berlin'" << endl;
	cout << "Interval<Time>: " << time_Itv.asString() << endl;

	system("pause");

	return 0;
}

// Program output:

// >> Interval Template Library: Sample interval.cpp <<
// ---------------------------------------------------
// Interval<int>: [3,7]
// Interval<double>: [0.707107,1.41421) does NOT contain sqrt(2)
// Interval<string>: (Barcelona,Boston] does NOT contain 'Barcelona'
// Interval<string>: (Barcelona,Boston] does  contain 'Berlin'
// Interval<Time>: (mon:08:30,mon:17:20)
